# Generated by Django 2.2.18 on 2024-12-22 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, help_text='Optional label for this plugin.', max_length=128, verbose_name='label')),
                ('id_name', models.CharField(blank=True, max_length=50, verbose_name='id name')),
                ('tag_type', models.CharField(choices=[('div', 'div'), ('header', 'header'), ('footer', 'footer'), ('article', 'article'), ('section', 'section')], default='div', max_length=50, verbose_name='tag Type')),
                ('background_repeat', models.CharField(blank=True, choices=[('repeat', 'repeat'), ('repeat-x', 'repeat-x'), ('repeat-y', 'repeat-y'), ('no-repeat', 'no-repeat'), ('initial', 'initial'), ('inherit', 'inherit')], default='repeat', max_length=128, null=True)),
                ('background_position', models.CharField(blank=True, max_length=128, null=True)),
                ('background_size', models.CharField(blank=True, help_text='auto|length|cover|contain|initial|inherit', max_length=128, null=True)),
                ('additional_class_names', models.TextField(blank=True, help_text='Comma separated list of additional classes to apply to tag_type', verbose_name='additional classes')),
                ('background_image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
